### ISSUE TITLE
Comparison coops by coop_handle_t

### ISSUE THREAD

**Issue by zumm** [Stiffstream/sobjectizer#15]
Any coop_handle_t is equivalent to any other coop_handle_t in the conditions like `if(handle_one == handle_two)`. Is it bug?

**Comment by eao197** [comment]
`coop_handle_t` has no comparison operators and isn't intended to be used in comparisons. I assume that in the case of `if(handle_one == handle_two)` you compare the results of conversion from `coop_handle_t` to `bool`.

If you want to compare coop_handles use `coop_handle_t::id()` method.

PS. Maybe comparison operators for `coop_handle_t` should be added in the future versions of SObjectizer.

**Comment by zumm** [comment]
Yes, i'm using `coop_handle_t::id()` now, but it feels a bit uncomfortable. Also that wrong equivalence is source of bugs i think. So comparison operators for `coop_handle_t `will be a great feature.
