### ISSUE TITLE
Comparison operators for coop_handle_t

### ISSUE THREAD

**Issue by eao197** [Stiffstream/sobjectizer#16]
The type `coop_handle_t` plays a role similar to the smart-pointer but doesn't have comparison operators. It could lead to unexpected result in the following case:
```cpp
so_5::coop_handle_t h1 = ...;
so_5::coop_handle_t h2 = ...;
if(h1 == h2) { // OOPS!
   ...
}
```
because the results of conversion from `coop_handle_t` to `bool` will be compared in `if(h1 == h2)`.

So it's can be desirable to have comparison operators for `coop_handle_t`.

**Comment by zumm** [comment]
Another problem: unable to using `coop_handle_t` as key in `std::map` or something like that.

**Comment by eao197** [comment]
Comparison operators added in the development branch: https://github.com/Stiffstream/sobjectizer/blob/918be391a8a3348f162cc67e82b0b27ca9691919/dev/so_5/coop_handle.hpp#L147-L181

I don't know when v.5.7.2 will be released. But you can use a version from a particular commit.

**Comment by eao197** [comment]
Now, this functionality is a part of v.5.7.2.
