### ISSUE TITLE
Wiki Pages, SO 5.6: Tutorial Basics, typo

### ISSUE THREAD

**Issue by sleeplynerd** [Stiffstream/sobjectizer#2]
On this page: https://github.com/Stiffstream/sobjectizer/wiki/SO-5.6-Tutorials-Basics

The listing for "Message Chains" section, class `data_producer`. According to the description provided above that listing, it should be `data_reader`, not `data_producer`.

**Comment by eao197** [comment]
Thanks for reporting this! It's fixed now.
