### ISSUE TITLE
Не удается включить work_thread_activity_tracking через params_tuner в wrapped_env_t

### ISSUE THREAD

**Issue by danemano** [Stiffstream/sobjectizer#21]
Здравствуйте, при попытке включить work_thread_activity_tracking:
so_5::wrapped_env_t env{..., [](auto& p){ p.turn_work_activity_tracking_on();});
auto result = env->environment().work_thread_actovity_tracking();
Ожидается, что result == on, но получается: result == unspecified.
Возможно значение флага теряется внутри конструктора копирования класса environment_params_t(environment.cpp):
... , m_work_thread_activity_tracking(work_thread_activity_tracking:: unspecified) ...
Это не выглядит правильным поведением.
Версия: 5.7.0 но мне кажется, что будет воспроизводиться и в последней.
Заранее спасибо.

**Comment by eao197** [comment]
Спасибо за информацию. Буду разбираться что к чему.

**Comment by eao197** [comment]
Еще раз спасибо. Действительно, был баг, который проявлялся именно при использовании wrapped_env. Запушил в рабочую ветку изменения. После прогона тестов волью правки в master и зафиксирую тег. Но это уже либо сегодня через 4-5 часов, либо уже завтра.

**Comment by danemano** [comment]
Спасибо за ответ

**Comment by eao197** [comment]
Вам спасибо за то, что указали на проблему.

Надеюсь, найдете SO-5 полезным для себя. Если что-то будет непонятно, то спрашивайте, не стесняйтесь. С удовольствием отвечу.
