### ISSUE TITLE
Wiki pages, SO 5.6: Tutorial Basics, another inconsistency found

### ISSUE THREAD

**Issue by sleeplynerd** [Stiffstream/sobjectizer#3]
Sorry, it's me again. 

On this page: https://github.com/Stiffstream/sobjectizer/wiki/SO-5.6-Tutorials-Basics

Section "Immutable and Mutable Messages". 

> Mutable messages can be sent to **MPMS** mboxes or mchains. But they can't be sent to MPMC mboxes (an exception will be thrown at such attempt).

Is MPMS meant to be either MPSC or MPMC?

**Comment by eao197** [comment]
MPSC
