### ISSUE TITLE
Any benchmark program available?

### ISSUE THREAD

**Issue by ilpropheta** [Stiffstream/sobjectizer#32]
Hi everyone,
this might be a weird question, please let me know if you need more context/information.

I am wondering if any of you has crafted a sort of _SObjectizer benchmark program_ to get some "generic" insights on the performance and throughput of SObjectizer on different machines and targets.

Alternatively, do you have any general tips to write such a program myself? Which kind of things would you measure? Can I use any performance tests you have released already?

Note: I already have performance tests covering **specific** applications, and I also produce profile reports. Instead, I need a quick way to test and get expectations on SObjectizer's capabilities on many machines (possibly built with proprietary hardware) subjected to different kind of load.

Many thanks!

Marco

**Comment by eao197** [comment]
Hi, Marco.

There is a set of different benchmarks we're using during the development of SObjectizer: https://github.com/Stiffstream/sobjectizer/tree/master/dev/test/so_5/bench
(but there are no CMake scripts for them because we not using CMake internally).

**Comment by ilpropheta** [comment]
Many thanks for pointing me to the right direction! Everything seems very well done! I'll have a closer look shortly.
If you have any tips on the common set of command line parameters to use, please let me know.

**Comment by Ultrafeel** [comment]
@eao197  I think you should add your library to [signal-slot-benchmarks](https://github.com/NoAvailableAlias/signal-slot-benchmarks) to gain more popularity. There are also forks of it: [andriskaaz signal-slot-benchmarks](https://github.com/andriskaaz/signal-slot-benchmarks), [VzdornovNA88 signal-slot-benchmarks](https://github.com/VzdornovNA88/signal-slot-benchmarks).
