### ISSUE TITLE
Backwards compatible way of closing mchains

### ISSUE THREAD

**Issue by ilpropheta** [Stiffstream/sobjectizer#41]
Hi! 
I have just seen the new release and I have a small suggestion for the wiki.

Since `abstract_message_chain_t::close(close_mode)` is now deprecated, I would explicitly mention on the release notes (wiki) how to replace this call (and related ones) with the new one in order to get the very same behavior. 

For example:

```cpp
close_retain_content(chain);
```

is now equivalent to:

```cpp
close_retain_content(so_5::exceptions_enabled, chain);
```

What do you think?

**Comment by eao197** [comment]
Hi!

I think you're right. I'll update the release notes later today.
