### ISSUE TITLE
Any way to wait until an agent is ready to receive messages?

### ISSUE THREAD

**Issue by ilpropheta** [Stiffstream/sobjectizer#49]
Hi,
I have a very simple question. Suppose I am testing an application where I have some agents registered to a global environment. 
I would like to be sure that such agents are ready to get messages from channels they have subscribed to. This way I can generate fake messages and make expectations.

At the moment, I just register them and wait - say - 10ms to be on the safe side. However, this is not portable and can fail sporadically on CI builds. In general, I don't like "sleep" of any sort.

Is it possible to wait for such a "state" without adding custom logic?
For example, agents have that `ensure_binding_finished`. Is this what I am looking for?

For the moment, I can't use the experimental "testing" capabilities in SObjectizer since I have some stable code that can't be easily accommodated to the "scenario" semantics.

Thanks!

**Comment by eao197** [comment]
Hi!

I added a new section to Wiki not so far ago. That section is related to coops and there is such thing as reg/dereg notitifcations: https://github.com/Stiffstream/sobjectizer/wiki/SO-5.7-InDepth-Coops#regdereg-notificators

Maybe reg-notificator can help you in your case.

There is also a possibility to set a global coop_listener: https://github.com/Stiffstream/sobjectizer/blob/master/dev/sample/so_5/coop_listener/main.cpp
This feature is not described well and is almost not used in SO-5, but can be useful too.

**Comment by ilpropheta** [comment]
Hi @eao197 ! 
Thanks for the reply. This seems to be helpful, but I don't understand one point: why is the notificator called on the same thread as that calling `register_coop`? Naively, for my scenario, I thought I needed something like this:

```cpp
auto childCoop = env.make_coop(parent, disp); // dispatcher here is active_group
some_event_type done;
childCoop->add_reg_notificator([&done, thisAgentCoopId = child->id()](so_5::environment_t&, const so_5::coop_handle_t& handle) noexcept {
	if (thisAgentCoopId == handle.id())
	{
		done.set();
	}
});
auto agent = child->make_agent<SomeAgentType>(...);
env.register_coop(std::move(child));
done.wait();
// at this point, the agent can receive messages (since child has been registered)
```

However, this code results in a deadlock.

Do you expect this?

**Comment by eao197** [comment]
> So is it guaranteed that, after returning from register_coop, every message sent to the mailboxes an agent has subscribed to will be delivered, sooner or later (depending on when the agent starts)?

If all subscriptions are made in `so_define_agent` and messages are sent after the return from `register_coop` then yes, guaranteed.

But there could be mbox types that requires subscription in `so_evt_start` ([retained_mbox](https://github.com/Stiffstream/so5extra/wiki/so5extra-1.5-Retained-Mbox#subscription-in-so_define_agent) for examples, the subscription in `so_define_agent` can lead to loss of some messages).

> Another related question: is there any way to check if an agent has started (still without adding custom logic)?

No, there is no such a way yet.

I'll think maybe some kind of hook can be defined for `so_evt_start` (or delivery of internal message that causes `so_evt_start`).
