### ISSUE TITLE
spinlock issue

### ISSUE THREAD

**Issue by makuzmenko** [Stiffstream/sobjectizer#88]
Hi! I've faced up the strange behavior of sobjectizer. 
With a load of only 700 messages per second (just receiving and not processing them), my program uses 60-70% of the CPU.
I got the application profile (linux perf) and the program spends most of the time in spinlock in so_5::disp::mpmc_queue_traits::combined_lock::actual_cond_t::wait. Is it a bug?
![image](https://github.com/user-attachments/assets/90e23ea8-5ab6-45cf-8d8a-0bd260ee56ed)

The FlameGraph is attached
![res5](https://github.com/user-attachments/assets/20f979d9-3467-4c9f-98ea-50fb482fc10b)

**Comment by eao197** [comment]
Hi!

It seems that you have to take a look at [this](https://github.com/Stiffstream/sobjectizer/wiki/SO-5.8-InDepth-Locks-Factory).
